config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rules
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
# frozen_string_literal: true

class Game
  include Mongoid::Document
  field :name, type: String
  field :handsize, type: Integer
  field :drawsize, type: Integer
  field :rules, type: Array, default: []
  field :goals, type: Array, default: []

  validates :drawsize, numericality: { only_integer: true }
  validates :handsize, numericality: { only_integer: true }
end

app/models/rule.rb
# frozen_string_literal: true

class Rule
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :group, type: String
  field :type, type: String
  field :entry_actions, type: Hash
  field :exit_actions, type: Hash

  validates :title, presence: true
  validates :description, presence: true
  validates :group, presence: true
  validates :type, format: { with: /(house|starter|normal)/ }, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all || []
  end

  # GET /games/1
  # GET /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:name, :handsize, :drawsize)
  end
end

app/controllers/rules_controller.rb
# frozen_string_literal: true

class RulesController < ApplicationController
  before_action :set_rule, only: %i[show edit update destroy]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show; end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit; end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rule
    @rule = Rule.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rule_params
    params.require(:rule).permit(:title, :description, :group, :type)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/rules_helper.rb
# frozen_string_literal: true

module RulesHelper
end

app/views/games/_form.html.haml
= form_with(model: game, local: true) do |form|
  - if game.errors.any?
    #error_explanation
      %h2
        = pluralize(game.errors.count, "error")
        prohibited this game from being saved:
      %ul
        - game.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name, id: :game_name
  .field
    = form.label :handsize
    = form.text_field :handsize, id: :game_handsize
  .field
    = form.label :drawsize
    = form.text_field :drawsize, id: :game_drawsize
  .field
    = form.label :rules
    = form.text_field :rules, id: :game_rules
  .field
    = form.label :goals
    = form.text_field :goals, id: :game_goals
  .actions
    = form.submit

app/views/games/edit.html.haml
%h1 Editing Game
= render 'form', game: @game
= link_to 'Show', @game
|
= link_to 'Back', games_path

app/views/games/index.html.haml
%p#notice= notice
%h1 Games
%table
  %thead
    %tr
      %th Name
      %th Handsize
      %th Drawsize
      %th{:colspan => "3"}
  %tbody
    - @games.each do |game|
      %tr
        %td= game.name
        %td= game.handsize
        %td= game.drawsize
        %td= link_to 'Show', game
        %td= link_to 'Edit', edit_game_path(game)
        %td= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Game', new_game_path

app/views/games/new.html.haml
%h1 New Game
= render 'form', game: @game
= link_to 'Back', games_path

app/views/games/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @game.name
%p
  %strong Handsize:
  = @game.handsize
%p
  %strong Drawsize:
  = @game.drawsize
%p
  %strong Rules:
  = @game.rules
%p
  %strong Goals:
  = @game.goals
= link_to 'Edit', edit_game_path(@game)
|
= link_to 'Back', games_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cards Against Humanity Flux
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/rules/_form.html.haml
= form_for @rule do |f|
  - if @rule.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rule.errors.count, "error")} prohibited this rule from being saved:"
      %ul
        - @rule.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :group
    = f.text_field :group
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :entry_actions
    = f.text_field :entry_actions
  .field
    = f.label :exit_actions
    = f.text_field :exit_actions
  .actions
    = f.submit 'Save'

app/views/rules/edit.html.haml
%h1 Editing rule

= render 'form'

= link_to 'Show', @rule
\|
= link_to 'Back', rules_path

app/views/rules/index.html.haml
%h1 Listing rules

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Group
      %th Type
      %th Entry actions
      %th Exit actions
      %th
      %th
      %th

  %tbody
    - @rules.each do |rule|
      %tr
        %td= rule.title
        %td= rule.description
        %td= rule.group
        %td= rule.type
        %td= rule.entry_actions
        %td= rule.exit_actions
        %td= link_to 'Show', rule
        %td= link_to 'Edit', edit_rule_path(rule)
        %td= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Rule', new_rule_path

app/views/rules/new.html.haml
%h1 New rule

= render 'form'

= link_to 'Back', rules_path

app/views/rules/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @rule.title
%p
  %b Description:
  = @rule.description
%p
  %b Group:
  = @rule.group
%p
  %b Type:
  = @rule.type
%p
  %b Entry actions:
  = @rule.entry_actions
%p
  %b Exit actions:
  = @rule.exit_actions

= link_to 'Edit', edit_rule_path(@rule)
\|
= link_to 'Back', rules_path